# create_project_structure.ps1
$ErrorActionPreference = "Stop"

$Root = "C:\development\Freight-Back-Office-OS"

$directories = @(
    "$Root\docs\architecture",
    "$Root\docs\api",
    "$Root\docs\product",
    "$Root\docs\runbooks",

    "$Root\infra\docker",
    "$Root\infra\nginx",
    "$Root\infra\github\workflows",
    "$Root\infra\scripts",
    "$Root\infra\k8s",

    "$Root\backend\app\core",
    "$Root\backend\app\domain\enums",
    "$Root\backend\app\domain\models",
    "$Root\backend\app\domain\value_objects",
    "$Root\backend\app\schemas",
    "$Root\backend\app\repositories",

    "$Root\backend\app\services\auth",
    "$Root\backend\app\services\ingestion",
    "$Root\backend\app\services\documents",
    "$Root\backend\app\services\ai\prompt_templates",
    "$Root\backend\app\services\validation\rules",
    "$Root\backend\app\services\workflow",
    "$Root\backend\app\services\notifications",
    "$Root\backend\app\services\loads",
    "$Root\backend\app\services\review",
    "$Root\backend\app\services\billing",
    "$Root\backend\app\services\onboarding",
    "$Root\backend\app\services\support",
    "$Root\backend\app\services\audit",

    "$Root\backend\app\workers\tasks",
    "$Root\backend\app\workers\schedulers",

    "$Root\backend\app\api\v1",
    "$Root\backend\app\utils",

    "$Root\backend\alembic\versions",

    "$Root\backend\tests\unit",
    "$Root\backend\tests\integration",
    "$Root\backend\tests\fixtures\sample_docs\ratecons",
    "$Root\backend\tests\fixtures\sample_docs\bols",
    "$Root\backend\tests\fixtures\sample_docs\invoices",
    "$Root\backend\tests\fixtures\payloads",

    "$Root\frontend\public",
    "$Root\frontend\src\app\(auth)\login",
    "$Root\frontend\src\app\dashboard\loads\[loadId]",
    "$Root\frontend\src\app\dashboard\drivers\[driverId]",
    "$Root\frontend\src\app\dashboard\review-queue",
    "$Root\frontend\src\app\dashboard\documents\[documentId]",
    "$Root\frontend\src\app\dashboard\notifications",
    "$Root\frontend\src\app\dashboard\onboarding",
    "$Root\frontend\src\app\dashboard\customers\[customerId]",
    "$Root\frontend\src\app\dashboard\billing\plans",
    "$Root\frontend\src\app\dashboard\billing\subscriptions",
    "$Root\frontend\src\app\dashboard\billing\invoices\[invoiceId]",
    "$Root\frontend\src\app\dashboard\billing\payments",
    "$Root\frontend\src\app\dashboard\support",
    "$Root\frontend\src\app\dashboard\settings",

    "$Root\frontend\src\app\driver-portal\uploads",
    "$Root\frontend\src\app\driver-portal\loads",
    "$Root\frontend\src\app\driver-portal\billing\invoices",
    "$Root\frontend\src\app\driver-portal\billing\payments",
    "$Root\frontend\src\app\driver-portal\support",

    "$Root\frontend\src\app\api\health",

    "$Root\frontend\src\components\layout",
    "$Root\frontend\src\components\dashboard",
    "$Root\frontend\src\components\loads",
    "$Root\frontend\src\components\drivers",
    "$Root\frontend\src\components\review",
    "$Root\frontend\src\components\documents",
    "$Root\frontend\src\components\onboarding",
    "$Root\frontend\src\components\customers",
    "$Root\frontend\src\components\billing",
    "$Root\frontend\src\components\support",
    "$Root\frontend\src\components\forms",
    "$Root\frontend\src\components\ui",

    "$Root\frontend\src\lib",
    "$Root\frontend\src\hooks",
    "$Root\frontend\src\types",
    "$Root\frontend\src\styles",

    "$Root\shared\contracts\api-schemas",
    "$Root\shared\samples",

    "$Root\data\seeds",
    "$Root\data\sandbox\uploaded-docs",
    "$Root\data\sandbox\extracted-results",
    "$Root\data\sandbox\test-results"
)

$files = @(
    "$Root\README.md",
    "$Root\.gitignore",
    "$Root\.editorconfig",
    "$Root\.env.example",
    "$Root\docker-compose.yml",
    "$Root\Makefile",
    "$Root\pyproject.toml",
    "$Root\package.json",

    "$Root\docs\architecture\system-overview.md",
    "$Root\docs\architecture\domain-model.md",
    "$Root\docs\architecture\workflow-engine.md",
    "$Root\docs\architecture\ai-integration.md",
    "$Root\docs\architecture\channel-ingestion.md",
    "$Root\docs\architecture\billing-architecture.md",
    "$Root\docs\architecture\onboarding-architecture.md",
    "$Root\docs\architecture\audit-and-observability.md",
    "$Root\docs\architecture\security-model.md",

    "$Root\docs\api\openapi-notes.md",
    "$Root\docs\api\endpoint-contracts.md",
    "$Root\docs\api\webhook-contracts.md",

    "$Root\docs\product\roadmap.md",
    "$Root\docs\product\v1-scope.md",
    "$Root\docs\product\pricing-model.md",
    "$Root\docs\product\billing-flows.md",
    "$Root\docs\product\onboarding-flows.md",
    "$Root\docs\product\backlog.md",

    "$Root\docs\runbooks\local-dev.md",
    "$Root\docs\runbooks\deployment.md",
    "$Root\docs\runbooks\billing-ops.md",
    "$Root\docs\runbooks\support-ops.md",
    "$Root\docs\runbooks\incident-response.md",

    "$Root\infra\docker\api.Dockerfile",
    "$Root\infra\docker\web.Dockerfile",
    "$Root\infra\docker\worker.Dockerfile",
    "$Root\infra\docker\nginx.Dockerfile",
    "$Root\infra\nginx\nginx.conf",
    "$Root\infra\github\workflows\api-ci.yml",
    "$Root\infra\github\workflows\web-ci.yml",
    "$Root\infra\github\workflows\worker-ci.yml",
    "$Root\infra\github\workflows\deploy.yml",
    "$Root\infra\scripts\bootstrap.ps1",
    "$Root\infra\scripts\bootstrap.sh",
    "$Root\infra\scripts\run-api.ps1",
    "$Root\infra\scripts\run-worker.ps1",
    "$Root\infra\scripts\run-web.ps1",
    "$Root\infra\scripts\seed-dev-data.ps1",
    "$Root\infra\scripts\reset-local-env.ps1",
    "$Root\infra\k8s\api-deployment.yaml",
    "$Root\infra\k8s\worker-deployment.yaml",
    "$Root\infra\k8s\web-deployment.yaml",
    "$Root\infra\k8s\redis.yaml",
    "$Root\infra\k8s\postgres.yaml",
    "$Root\infra\k8s\minio.yaml",

    "$Root\backend\alembic.ini",
    "$Root\backend\pytest.ini",

    "$Root\backend\app\main.py",
    "$Root\backend\app\lifespan.py",

    "$Root\backend\app\core\config.py",
    "$Root\backend\app\core\constants.py",
    "$Root\backend\app\core\database.py",
    "$Root\backend\app\core\security.py",
    "$Root\backend\app\core\logging.py",
    "$Root\backend\app\core\middleware.py",
    "$Root\backend\app\core\dependencies.py",
    "$Root\backend\app\core\exceptions.py",
    "$Root\backend\app\core\idempotency.py",
    "$Root\backend\app\core\feature_flags.py",
    "$Root\backend\app\core\healthchecks.py",

    "$Root\backend\app\domain\enums\channel.py",
    "$Root\backend\app\domain\enums\document_type.py",
    "$Root\backend\app\domain\enums\load_status.py",
    "$Root\backend\app\domain\enums\processing_status.py",
    "$Root\backend\app\domain\enums\notification_status.py",
    "$Root\backend\app\domain\enums\role.py",
    "$Root\backend\app\domain\enums\onboarding_status.py",
    "$Root\backend\app\domain\enums\customer_account_status.py",
    "$Root\backend\app\domain\enums\subscription_status.py",
    "$Root\backend\app\domain\enums\billing_cycle.py",
    "$Root\backend\app\domain\enums\invoice_status.py",
    "$Root\backend\app\domain\enums\payment_status.py",
    "$Root\backend\app\domain\enums\payment_provider.py",
    "$Root\backend\app\domain\enums\payment_method_type.py",
    "$Root\backend\app\domain\enums\validation_severity.py",
    "$Root\backend\app\domain\enums\audit_actor_type.py",

    "$Root\backend\app\domain\models\organization.py",
    "$Root\backend\app\domain\models\customer_account.py",
    "$Root\backend\app\domain\models\onboarding_checklist.py",
    "$Root\backend\app\domain\models\referral.py",
    "$Root\backend\app\domain\models\staff_user.py",
    "$Root\backend\app\domain\models\driver.py",
    "$Root\backend\app\domain\models\broker.py",
    "$Root\backend\app\domain\models\load.py",
    "$Root\backend\app\domain\models\load_document.py",
    "$Root\backend\app\domain\models\extracted_field.py",
    "$Root\backend\app\domain\models\validation_issue.py",
    "$Root\backend\app\domain\models\workflow_event.py",
    "$Root\backend\app\domain\models\notification.py",
    "$Root\backend\app\domain\models\audit_log.py",
    "$Root\backend\app\domain\models\service_plan.py",
    "$Root\backend\app\domain\models\subscription.py",
    "$Root\backend\app\domain\models\usage_record.py",
    "$Root\backend\app\domain\models\billing_invoice.py",
    "$Root\backend\app\domain\models\billing_invoice_line.py",
    "$Root\backend\app\domain\models\payment_method.py",
    "$Root\backend\app\domain\models\payment.py",
    "$Root\backend\app\domain\models\ledger_entry.py",
    "$Root\backend\app\domain\models\support_ticket.py",
    "$Root\backend\app\domain\models\api_client.py",

    "$Root\backend\app\domain\value_objects\money.py",
    "$Root\backend\app\domain\value_objects\phone_number.py",
    "$Root\backend\app\domain\value_objects\confidence_score.py",
    "$Root\backend\app\domain\value_objects\date_range.py",

    "$Root\backend\app\schemas\auth.py",
    "$Root\backend\app\schemas\organization.py",
    "$Root\backend\app\schemas\customer_account.py",
    "$Root\backend\app\schemas\onboarding.py",
    "$Root\backend\app\schemas\referral.py",
    "$Root\backend\app\schemas\staff_user.py",
    "$Root\backend\app\schemas\driver.py",
    "$Root\backend\app\schemas\broker.py",
    "$Root\backend\app\schemas\load.py",
    "$Root\backend\app\schemas\document.py",
    "$Root\backend\app\schemas\extraction.py",
    "$Root\backend\app\schemas\validation.py",
    "$Root\backend\app\schemas\workflow.py",
    "$Root\backend\app\schemas\notification.py",
    "$Root\backend\app\schemas\dashboard.py",
    "$Root\backend\app\schemas\billing.py",
    "$Root\backend\app\schemas\service_plan.py",
    "$Root\backend\app\schemas\subscription.py",
    "$Root\backend\app\schemas\invoice.py",
    "$Root\backend\app\schemas\payment.py",
    "$Root\backend\app\schemas\support.py",
    "$Root\backend\app\schemas\webhook_whatsapp.py",
    "$Root\backend\app\schemas\webhook_email.py",
    "$Root\backend\app\schemas\webhook_payment.py",
    "$Root\backend\app\schemas\health.py",

    "$Root\backend\app\repositories\organization_repo.py",
    "$Root\backend\app\repositories\customer_account_repo.py",
    "$Root\backend\app\repositories\onboarding_repo.py",
    "$Root\backend\app\repositories\referral_repo.py",
    "$Root\backend\app\repositories\staff_user_repo.py",
    "$Root\backend\app\repositories\driver_repo.py",
    "$Root\backend\app\repositories\broker_repo.py",
    "$Root\backend\app\repositories\load_repo.py",
    "$Root\backend\app\repositories\document_repo.py",
    "$Root\backend\app\repositories\extracted_field_repo.py",
    "$Root\backend\app\repositories\validation_repo.py",
    "$Root\backend\app\repositories\workflow_event_repo.py",
    "$Root\backend\app\repositories\notification_repo.py",
    "$Root\backend\app\repositories\audit_repo.py",
    "$Root\backend\app\repositories\service_plan_repo.py",
    "$Root\backend\app\repositories\subscription_repo.py",
    "$Root\backend\app\repositories\usage_record_repo.py",
    "$Root\backend\app\repositories\billing_invoice_repo.py",
    "$Root\backend\app\repositories\payment_method_repo.py",
    "$Root\backend\app\repositories\payment_repo.py",
    "$Root\backend\app\repositories\ledger_repo.py",
    "$Root\backend\app\repositories\support_ticket_repo.py",

    "$Root\backend\app\services\auth\auth_service.py",
    "$Root\backend\app\services\auth\token_service.py",

    "$Root\backend\app\services\ingestion\ingestion_router.py",
    "$Root\backend\app\services\ingestion\channel_dispatcher.py",
    "$Root\backend\app\services\ingestion\upload_service.py",
    "$Root\backend\app\services\ingestion\whatsapp_ingestion_service.py",
    "$Root\backend\app\services\ingestion\email_ingestion_service.py",
    "$Root\backend\app\services\ingestion\api_ingestion_service.py",

    "$Root\backend\app\services\documents\document_service.py",
    "$Root\backend\app\services\documents\document_classifier.py",
    "$Root\backend\app\services\documents\document_linker.py",
    "$Root\backend\app\services\documents\file_fingerprint_service.py",
    "$Root\backend\app\services\documents\storage_service.py",

    "$Root\backend\app\services\ai\extraction_service.py",
    "$Root\backend\app\services\ai\ocr_service.py",
    "$Root\backend\app\services\ai\llm_service.py",
    "$Root\backend\app\services\ai\confidence_service.py",
    "$Root\backend\app\services\ai\anomaly_detection_service.py",
    "$Root\backend\app\services\ai\prompt_templates\ratecon_extraction.txt",
    "$Root\backend\app\services\ai\prompt_templates\bol_extraction.txt",
    "$Root\backend\app\services\ai\prompt_templates\invoice_extraction.txt",
    "$Root\backend\app\services\ai\prompt_templates\validation_assist.txt",

    "$Root\backend\app\services\validation\validation_engine.py",
    "$Root\backend\app\services\validation\validation_orchestrator.py",
    "$Root\backend\app\services\validation\rules\missing_signature.py",
    "$Root\backend\app\services\validation\rules\amount_mismatch.py",
    "$Root\backend\app\services\validation\rules\duplicate_load.py",
    "$Root\backend\app\services\validation\rules\missing_required_fields.py",
    "$Root\backend\app\services\validation\rules\unreadable_document.py",
    "$Root\backend\app\services\validation\rules\broker_consistency.py",

    "$Root\backend\app\services\workflow\workflow_engine.py",
    "$Root\backend\app\services\workflow\state_machine.py",
    "$Root\backend\app\services\workflow\transitions.py",
    "$Root\backend\app\services\workflow\event_publisher.py",

    "$Root\backend\app\services\notifications\notification_service.py",
    "$Root\backend\app\services\notifications\whatsapp_service.py",
    "$Root\backend\app\services\notifications\email_service.py",
    "$Root\backend\app\services\notifications\inapp_service.py",
    "$Root\backend\app\services\notifications\template_service.py",

    "$Root\backend\app\services\loads\load_service.py",
    "$Root\backend\app\services\loads\load_matching_service.py",
    "$Root\backend\app\services\loads\load_summary_service.py",
    "$Root\backend\app\services\loads\driver_load_timeline_service.py",

    "$Root\backend\app\services\review\review_queue_service.py",
    "$Root\backend\app\services\review\human_review_service.py",

    "$Root\backend\app\services\billing\billing_service.py",
    "$Root\backend\app\services\billing\pricing_service.py",
    "$Root\backend\app\services\billing\subscription_service.py",
    "$Root\backend\app\services\billing\invoice_service.py",
    "$Root\backend\app\services\billing\payment_service.py",
    "$Root\backend\app\services\billing\usage_billing_service.py",
    "$Root\backend\app\services\billing\ledger_service.py",
    "$Root\backend\app\services\billing\dunning_service.py",

    "$Root\backend\app\services\onboarding\onboarding_service.py",
    "$Root\backend\app\services\onboarding\customer_account_service.py",
    "$Root\backend\app\services\onboarding\referral_service.py",

    "$Root\backend\app\services\support\support_service.py",
    "$Root\backend\app\services\support\ticket_routing_service.py",

    "$Root\backend\app\services\audit\audit_service.py",

    "$Root\backend\app\workers\celery_app.py",
    "$Root\backend\app\workers\queues.py",
    "$Root\backend\app\workers\tasks\process_document.py",
    "$Root\backend\app\workers\tasks\classify_document.py",
    "$Root\backend\app\workers\tasks\extract_fields.py",
    "$Root\backend\app\workers\tasks\run_validation.py",
    "$Root\backend\app\workers\tasks\send_notification.py",
    "$Root\backend\app\workers\tasks\reconcile_status.py",
    "$Root\backend\app\workers\tasks\generate_recurring_invoices.py",
    "$Root\backend\app\workers\tasks\collect_payment.py",
    "$Root\backend\app\workers\tasks\mark_overdue_invoices.py",
    "$Root\backend\app\workers\tasks\send_billing_reminders.py",
    "$Root\backend\app\workers\tasks\sync_payment_webhooks.py",
    "$Root\backend\app\workers\schedulers\periodic_jobs.py",

    "$Root\backend\app\api\router.py",
    "$Root\backend\app\api\v1\auth.py",
    "$Root\backend\app\api\v1\organizations.py",
    "$Root\backend\app\api\v1\customer_accounts.py",
    "$Root\backend\app\api\v1\onboarding.py",
    "$Root\backend\app\api\v1\referrals.py",
    "$Root\backend\app\api\v1\staff_users.py",
    "$Root\backend\app\api\v1\drivers.py",
    "$Root\backend\app\api\v1\brokers.py",
    "$Root\backend\app\api\v1\loads.py",
    "$Root\backend\app\api\v1\documents.py",
    "$Root\backend\app\api\v1\review_queue.py",
    "$Root\backend\app\api\v1\dashboard.py",
    "$Root\backend\app\api\v1\notifications.py",
    "$Root\backend\app\api\v1\service_plans.py",
    "$Root\backend\app\api\v1\subscriptions.py",
    "$Root\backend\app\api\v1\billing_invoices.py",
    "$Root\backend\app\api\v1\payments.py",
    "$Root\backend\app\api\v1\billing_dashboard.py",
    "$Root\backend\app\api\v1\support.py",
    "$Root\backend\app\api\v1\webhooks_whatsapp.py",
    "$Root\backend\app\api\v1\webhooks_email.py",
    "$Root\backend\app\api\v1\webhooks_payment.py",
    "$Root\backend\app\api\v1\health.py",

    "$Root\backend\app\utils\datetime_utils.py",
    "$Root\backend\app\utils\file_utils.py",
    "$Root\backend\app\utils\phone_utils.py",
    "$Root\backend\app\utils\text_utils.py",
    "$Root\backend\app\utils\money_utils.py",

    "$Root\backend\alembic\env.py",
    "$Root\backend\alembic\script.py.mako",

    "$Root\backend\tests\conftest.py",
    "$Root\backend\tests\unit\test_validation_rules.py",
    "$Root\backend\tests\unit\test_workflow_engine.py",
    "$Root\backend\tests\unit\test_extraction_service.py",
    "$Root\backend\tests\unit\test_load_service.py",
    "$Root\backend\tests\unit\test_subscription_service.py",
    "$Root\backend\tests\unit\test_invoice_service.py",
    "$Root\backend\tests\unit\test_payment_service.py",

    "$Root\backend\tests\integration\test_document_upload.py",
    "$Root\backend\tests\integration\test_whatsapp_webhook.py",
    "$Root\backend\tests\integration\test_review_queue.py",
    "$Root\backend\tests\integration\test_load_lifecycle.py",
    "$Root\backend\tests\integration\test_subscription_flow.py",
    "$Root\backend\tests\integration\test_invoice_generation.py",
    "$Root\backend\tests\integration\test_payment_webhook.py",

    "$Root\frontend\next.config.ts",
    "$Root\frontend\tsconfig.json",
    "$Root\frontend\postcss.config.js",
    "$Root\frontend\tailwind.config.ts",

    "$Root\frontend\public\logo.svg",
    "$Root\frontend\public\favicon.ico",

    "$Root\frontend\src\app\(auth)\login\page.tsx",
    "$Root\frontend\src\app\(auth)\layout.tsx",

    "$Root\frontend\src\app\dashboard\page.tsx",
    "$Root\frontend\src\app\dashboard\loads\page.tsx",
    "$Root\frontend\src\app\dashboard\loads\[loadId]\page.tsx",
    "$Root\frontend\src\app\dashboard\drivers\page.tsx",
    "$Root\frontend\src\app\dashboard\drivers\[driverId]\page.tsx",
    "$Root\frontend\src\app\dashboard\review-queue\page.tsx",
    "$Root\frontend\src\app\dashboard\documents\[documentId]\page.tsx",
    "$Root\frontend\src\app\dashboard\notifications\page.tsx",
    "$Root\frontend\src\app\dashboard\onboarding\page.tsx",
    "$Root\frontend\src\app\dashboard\customers\page.tsx",
    "$Root\frontend\src\app\dashboard\customers\[customerId]\page.tsx",
    "$Root\frontend\src\app\dashboard\billing\page.tsx",
    "$Root\frontend\src\app\dashboard\billing\plans\page.tsx",
    "$Root\frontend\src\app\dashboard\billing\subscriptions\page.tsx",
    "$Root\frontend\src\app\dashboard\billing\invoices\page.tsx",
    "$Root\frontend\src\app\dashboard\billing\invoices\[invoiceId]\page.tsx",
    "$Root\frontend\src\app\dashboard\billing\payments\page.tsx",
    "$Root\frontend\src\app\dashboard\support\page.tsx",
    "$Root\frontend\src\app\dashboard\settings\page.tsx",

    "$Root\frontend\src\app\driver-portal\page.tsx",
    "$Root\frontend\src\app\driver-portal\uploads\page.tsx",
    "$Root\frontend\src\app\driver-portal\loads\page.tsx",
    "$Root\frontend\src\app\driver-portal\billing\page.tsx",
    "$Root\frontend\src\app\driver-portal\billing\invoices\page.tsx",
    "$Root\frontend\src\app\driver-portal\billing\payments\page.tsx",
    "$Root\frontend\src\app\driver-portal\support\page.tsx",

    "$Root\frontend\src\app\api\health\route.ts",
    "$Root\frontend\src\app\layout.tsx",
    "$Root\frontend\src\app\page.tsx",

    "$Root\frontend\src\lib\api-client.ts",
    "$Root\frontend\src\lib\auth.ts",
    "$Root\frontend\src\lib\config.ts",
    "$Root\frontend\src\lib\formatters.ts",
    "$Root\frontend\src\lib\validators.ts",
    "$Root\frontend\src\lib\billing.ts",

    "$Root\frontend\src\hooks\useLoads.ts",
    "$Root\frontend\src\hooks\useDrivers.ts",
    "$Root\frontend\src\hooks\useReviewQueue.ts",
    "$Root\frontend\src\hooks\useNotifications.ts",
    "$Root\frontend\src\hooks\useBilling.ts",
    "$Root\frontend\src\hooks\useCustomerAccounts.ts",

    "$Root\frontend\src\types\auth.ts",
    "$Root\frontend\src\types\load.ts",
    "$Root\frontend\src\types\driver.ts",
    "$Root\frontend\src\types\document.ts",
    "$Root\frontend\src\types\dashboard.ts",
    "$Root\frontend\src\types\billing.ts",
    "$Root\frontend\src\types\invoice.ts",
    "$Root\frontend\src\types\payment.ts",
    "$Root\frontend\src\types\customer.ts",

    "$Root\frontend\src\styles\globals.css",

    "$Root\shared\contracts\load-status.ts",
    "$Root\shared\contracts\document-types.ts",
    "$Root\shared\contracts\channel-types.ts",
    "$Root\shared\contracts\billing-types.ts",

    "$Root\shared\samples\ratecon-sample.json",
    "$Root\shared\samples\bol-sample.json",
    "$Root\shared\samples\invoice-sample.json",
    "$Root\shared\samples\webhook-payloads.json",

    "$Root\data\seeds\organizations.json",
    "$Root\data\seeds\customer_accounts.json",
    "$Root\data\seeds\drivers.json",
    "$Root\data\seeds\brokers.json",
    "$Root\data\seeds\service_plans.json",
    "$Root\data\seeds\staff_users.json"
)

Write-Host "Creating directories..."
foreach ($dir in $directories) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

Write-Host "Creating files..."
foreach ($file in $files) {
    $parent = Split-Path -Parent $file
    if (-not (Test-Path $parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }

    if (-not (Test-Path $file)) {
        New-Item -ItemType File -Path $file -Force | Out-Null
    }
}

Write-Host ""
Write-Host "Project structure created successfully at: $Root" -ForegroundColor Green