from __future__ import annotations

from types import MappingProxyType

from app.core.config import get_settings


def _settings():
    return get_settings()


APP_NAME = _settings().app_name
APP_VERSION = _settings().app_version
API_V1_PREFIX = _settings().api_v1_prefix

DEFAULT_TIMEZONE = "America/Toronto"
DEFAULT_CURRENCY_CODE = "USD"

REQUEST_ID_HEADER = "X-Request-ID"

SUPPORTED_UPLOAD_MIME_TYPES = frozenset(
    {
        "application/pdf",
        "image/jpeg",
        "image/jpg",
        "image/png",
        "image/webp",
    }
)

MAX_UPLOAD_SIZE_BYTES = 25 * 1024 * 1024

LOAD_STATUS_BOOKED = "booked"
LOAD_STATUS_IN_TRANSIT = "in_transit"
LOAD_STATUS_DELIVERED = "delivered"
LOAD_STATUS_DOCS_RECEIVED = "docs_received"
LOAD_STATUS_DOCS_NEEDS_ATTENTION = "docs_needs_attention"
LOAD_STATUS_INVOICE_READY = "invoice_ready"
LOAD_STATUS_SUBMITTED_TO_BROKER = "submitted_to_broker"
LOAD_STATUS_SUBMITTED_TO_FACTORING = "submitted_to_factoring"
LOAD_STATUS_PACKET_REJECTED = "packet_rejected"
LOAD_STATUS_RESUBMISSION_NEEDED = "resubmission_needed"
LOAD_STATUS_ADVANCE_PAID = "advance_paid"
LOAD_STATUS_RESERVE_PENDING = "reserve_pending"
LOAD_STATUS_FULLY_PAID = "fully_paid"
LOAD_STATUS_SHORT_PAID = "short_paid"
LOAD_STATUS_DISPUTED = "disputed"
LOAD_STATUS_ARCHIVED = "archived"

LOAD_STATUSES = (
    LOAD_STATUS_BOOKED,
    LOAD_STATUS_IN_TRANSIT,
    LOAD_STATUS_DELIVERED,
    LOAD_STATUS_DOCS_RECEIVED,
    LOAD_STATUS_DOCS_NEEDS_ATTENTION,
    LOAD_STATUS_INVOICE_READY,
    LOAD_STATUS_SUBMITTED_TO_BROKER,
    LOAD_STATUS_SUBMITTED_TO_FACTORING,
    LOAD_STATUS_PACKET_REJECTED,
    LOAD_STATUS_RESUBMISSION_NEEDED,
    LOAD_STATUS_ADVANCE_PAID,
    LOAD_STATUS_RESERVE_PENDING,
    LOAD_STATUS_FULLY_PAID,
    LOAD_STATUS_SHORT_PAID,
    LOAD_STATUS_DISPUTED,
    LOAD_STATUS_ARCHIVED,
)

ACTIVE_LOAD_STATUSES = (
    LOAD_STATUS_BOOKED,
    LOAD_STATUS_IN_TRANSIT,
    LOAD_STATUS_DELIVERED,
    LOAD_STATUS_DOCS_RECEIVED,
    LOAD_STATUS_DOCS_NEEDS_ATTENTION,
    LOAD_STATUS_INVOICE_READY,
    LOAD_STATUS_SUBMITTED_TO_BROKER,
    LOAD_STATUS_SUBMITTED_TO_FACTORING,
    LOAD_STATUS_PACKET_REJECTED,
    LOAD_STATUS_RESUBMISSION_NEEDED,
    LOAD_STATUS_ADVANCE_PAID,
    LOAD_STATUS_RESERVE_PENDING,
    LOAD_STATUS_SHORT_PAID,
    LOAD_STATUS_DISPUTED,
)

TERMINAL_LOAD_STATUSES = (
    LOAD_STATUS_FULLY_PAID,
    LOAD_STATUS_ARCHIVED,
)

PROCESSING_STATUS_PENDING = "pending"
PROCESSING_STATUS_IN_PROGRESS = "in_progress"
PROCESSING_STATUS_COMPLETED = "completed"
PROCESSING_STATUS_FAILED = "failed"

PROCESSING_STATUSES = (
    PROCESSING_STATUS_PENDING,
    PROCESSING_STATUS_IN_PROGRESS,
    PROCESSING_STATUS_COMPLETED,
    PROCESSING_STATUS_FAILED,
)

CHANNEL_WEB = "web"
CHANNEL_WHATSAPP = "whatsapp"
CHANNEL_EMAIL = "email"
CHANNEL_API = "api"
CHANNEL_MANUAL = "manual"

CHANNELS = (
    CHANNEL_WEB,
    CHANNEL_WHATSAPP,
    CHANNEL_EMAIL,
    CHANNEL_API,
    CHANNEL_MANUAL,
)

DOCUMENT_TYPE_RATE_CONFIRMATION = "rate_confirmation"
DOCUMENT_TYPE_BILL_OF_LADING = "bill_of_lading"
DOCUMENT_TYPE_INVOICE = "invoice"
DOCUMENT_TYPE_PROOF_OF_DELIVERY = "proof_of_delivery"
DOCUMENT_TYPE_OTHER = "other"
DOCUMENT_TYPE_UNKNOWN = "unknown"

DOCUMENT_TYPES = (
    DOCUMENT_TYPE_RATE_CONFIRMATION,
    DOCUMENT_TYPE_BILL_OF_LADING,
    DOCUMENT_TYPE_INVOICE,
    DOCUMENT_TYPE_PROOF_OF_DELIVERY,
    DOCUMENT_TYPE_OTHER,
    DOCUMENT_TYPE_UNKNOWN,
)

NOTIFICATION_CHANNEL_WHATSAPP = "whatsapp"
NOTIFICATION_CHANNEL_EMAIL = "email"
NOTIFICATION_CHANNEL_SMS = "sms"
NOTIFICATION_CHANNEL_IN_APP = "in_app"

NOTIFICATION_CHANNELS = (
    NOTIFICATION_CHANNEL_WHATSAPP,
    NOTIFICATION_CHANNEL_EMAIL,
    NOTIFICATION_CHANNEL_SMS,
    NOTIFICATION_CHANNEL_IN_APP,
)

NOTIFICATION_STATUS_QUEUED = "queued"
NOTIFICATION_STATUS_SENT = "sent"
NOTIFICATION_STATUS_DELIVERED = "delivered"
NOTIFICATION_STATUS_READ = "read"
NOTIFICATION_STATUS_FAILED = "failed"
NOTIFICATION_STATUS_RECEIVED = "received"

NOTIFICATION_STATUSES = (
    NOTIFICATION_STATUS_QUEUED,
    NOTIFICATION_STATUS_SENT,
    NOTIFICATION_STATUS_DELIVERED,
    NOTIFICATION_STATUS_READ,
    NOTIFICATION_STATUS_FAILED,
    NOTIFICATION_STATUS_RECEIVED,
)

ROLE_OWNER = "owner"
ROLE_ADMIN = "admin"
ROLE_OPS_MANAGER = "ops_manager"
ROLE_OPS_AGENT = "ops_agent"
ROLE_BILLING_ADMIN = "billing_admin"
ROLE_SUPPORT_AGENT = "support_agent"
ROLE_VIEWER = "viewer"

STAFF_ROLES = (
    ROLE_OWNER,
    ROLE_ADMIN,
    ROLE_OPS_MANAGER,
    ROLE_OPS_AGENT,
    ROLE_BILLING_ADMIN,
    ROLE_SUPPORT_AGENT,
    ROLE_VIEWER,
)

STATUS_GROUPS = MappingProxyType(
    {
        "load": LOAD_STATUSES,
        "processing": PROCESSING_STATUSES,
        "notification": NOTIFICATION_STATUSES,
    }
)
